Allow easily searching for suppliersReference and specialInstructions
guardian/grid pull request #3036
Opened 2020-10-26 01:46 UTC by paperboyo

Replaces https://github.com/guardian/grid/pull/2716.

This allow searching for both these as fields (and chips) and also in free-text search. Currently, for some unknown reason, 
suppliersReference search by-field, doesn’t work (I’ve tried bot `keywordField` and `standardAnalysed` mapping! I would love to be told what’s wrong. Even more so, because this change requires re-mapping (so, a [reindex](https://github.com/guardian/grid/tree/main/scripts#scripts)).

## How can success be measured?
Terms from (parts of) specialInstructions show up in free-text search. One can easily search for specialReference.

## Who should look at this?
Will shyly ask Akash.

## Tested?
- [x] locally
- [ ] on TEST

2020-10-28 14:14 UTC, AWare approved these changes

2020-11-30 15:36 UTC, AWare requested changes
Having some issues running a remap locally so putting a hold on this pr until resolved. 
<img width="894" alt="image" src="https://user-images.githubusercontent.com/2670496/100629978-daa33b00-3321-11eb-91d4-f463b5bace6b.png">

2021-05-28 16:55 UTC, AWare commented
I think we should review this before we reingest.

2022-09-01 11:01 UTC, andrew-nowak approved these changes
tested on test, lgtm!

2022-09-02 10:07 UTC, merged