Extract Staff Photographer Organisation to config
guardian/grid pull request #3312
Opened 2021-05-19 12:42 UTC by adrielulanovsky

## What does this change?
When an image is from a staff photographer, this allows to configure the alt text the image will show as "{staffOrg}-owned: ..." instead of "GNM-owned: ..."

## How can success be measured?
- The Guardian still sees the alt text as "GNM-owned: ..."
- BBC sees the alt text as "BBC-owned: ..."

## Screenshots
![image](https://user-images.githubusercontent.com/20479781/118814404-8287d300-b886-11eb-9e77-647ae86003d9.png)

## Who should look at this?
@guardian/digital-cms

## Tested?
- [ ] locally by committer
- [ ] locally by Guardian reviewer
- [ ] on the Guardian's TEST environment

2021-05-19 12:44 UTC, AWare approved these changes
GNM is hardwired as default so no need for a config change. Will check on TEST before merge but otherwise 👍

2021-05-19 12:44 UTC, paperboyo commented
Cool! Would it be also worth changing the wording on the `+is` chips?

<img width="268" alt="image" src="https://user-images.githubusercontent.com/6032869/118814699-53825900-b8a8-11eb-8946-735e07bea3b1.png">

2021-05-19 12:47 UTC, adrielulanovsky commented
> Cool! Would it be also worth changing the wording on the `+is` chips?
> 
> <img alt="image" width="268" src="https://user-images.githubusercontent.com/6032869/118814699-53825900-b8a8-11eb-8946-735e07bea3b1.png">

Yes, I'll take a look into that as well. Thanks for noticing this

2021-05-19 12:52 UTC, AWare approved these changes
I spoke too soon, it doesn't want to compile. 

`(kahuna / Compile / compileIncremental) Compilation failed`

2021-05-19 12:53 UTC, AWare requested changes
Apologies, I meant

2021-05-19 12:55 UTC, adrielulanovsky commented
> I spoke too soon, it doesn't want to compile.
> 
> `(kahuna / Compile / compileIncremental) Compilation failed`

My bad, I renamed "organization" to "organisation" but forgot about one instance, sorry for that. Will fix now

2021-05-19 15:51 UTC, adrielulanovsky commented
@AWare @paperboyo Updated PR with compiling error fix and IsFilter changes

2021-05-20 10:15 UTC, AWare approved these changes
@paperboyo is taking this for a spin on TEST, otherwise happy.

2021-05-20 12:47 UTC, merged