Change warning message in usage deletion
guardian/grid pull request #3326
Opened 2021-05-25 19:08 UTC by adrielulanovsky

## What does this change?
This changes the alert message that pops up when trying to delete an image's usages. The text change is intended to remove ambiguity and make clear that the image itself won't be deleted, only the usages.

## How can success be measured?
The text shown in the alert displays the following text:

You're about to delete ALL USAGE INFORMATION for this image.
This will NOT remove the image from places it's been used in, but it WILL remove all the details of who and where used it.
Enter DELETE below to confirm

## Who should look at this?
@guardian/digital-cms

## Tested?
- [ ] locally by committer
- [ ] locally by Guardian reviewer
- [ ] on the Guardian's TEST environment

2021-05-25 19:09 UTC, paperboyo approved these changes
As this is messaging only, 👍. Also, much clearer, thanks!

2021-05-26 10:34 UTC, paperboyo requested changes
Sorry, just spotted lack of curly quotes. Nitpick.

2021-05-26 10:34 UTC, paperboyo commented on kahuna/public/js/components/gr-delete-usages/gr-delete-usages.js
> +            |This will NOT remove the image from places it's been used in,
```suggestion
            |This will NOT remove the image from places it’s been used in,
```

2021-05-26 10:34 UTC, paperboyo commented on kahuna/public/js/components/gr-delete-usages/gr-delete-usages.js
> +            |You're about to delete ALL USAGE INFORMATION for this image.
```suggestion
            |You’re about to delete ALL USAGE INFORMATION for this image.
```

2021-05-26 10:34 UTC, paperboyo commented on kahuna/public/js/components/gr-delete-usages/gr-delete-usages.js
> +            |This will NOT remove the image from places it's been used in,
```suggestion
            |This will NOT remove the image from places it’s been used in,
```

2021-05-26 16:16 UTC, adrielulanovsky commented on kahuna/public/js/components/gr-delete-usages/gr-delete-usages.js
> +            |This will NOT remove the image from places it's been used in,
Fixed

2021-05-26 16:16 UTC, adrielulanovsky commented on kahuna/public/js/components/gr-delete-usages/gr-delete-usages.js
> +            |You're about to delete ALL USAGE INFORMATION for this image.
Fixed

2021-05-26 16:16 UTC, adrielulanovsky commented on kahuna/public/js/components/gr-delete-usages/gr-delete-usages.js
> +            |This will NOT remove the image from places it's been used in,
Fixed

2021-05-26 16:38 UTC, paperboyo approved these changes

2021-05-26 16:39 UTC, merged